apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: daily-digest-data
  namespace: daily-digest
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi
