apiVersion: v1
kind: Service
metadata:
  name: spool
  namespace: default
  labels:
    app: spool
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: spool
  type: ClusterIP
