image:
  repository: reader-image
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: reader.daily-digest.local
  entryPoints:
    - websecure
  middlewares:
    - name: authentik-auth

replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
