apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "api.fullname" . }}-data
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.db.storageClass }}
  resources:
    requests:
      storage: {{ .Values.db.size }}
