apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spool.fullname" . }}-secrets
  labels:
    {{- include "spool.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.youtubeApiKey }}
  YOUTUBE_API_KEY: {{ .Values.secrets.youtubeApiKey | b64enc | quote }}
  {{- end }}
