image:
  repository: api-image
  tag: latest
  pullPolicy: IfNotPresent

db:
  path: /app/data/daily-digest.db
  storageClass: ""
  size: 1Gi

inference:
  providerUrl: http://litellm.litellm.svc.cluster.local:4000
  summarizationModel: huggingface/llama-3.2-3b-instruct

service:
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true

replicaCount: 1
