image:
  repository: api-image
  tag: latest
  pullPolicy: IfNotPresent

db:
  storageClass: nfs
  size: 1Gi

service:
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true

replicaCount: 1
