apiVersion: v1
kind: Service
metadata:
  name: {{ include "reader.fullname" . }}
  labels:
    {{- include "reader.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "reader.selectorLabels" . | nindent 4 }}
