apiVersion: v1
kind: Service
metadata:
  name: {{ include "spool.name" . }}
  labels:
    {{- include "spool.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "spool.selectorLabels" . | nindent 4 }}
